# Generated by Django 5.2.7 on 2025-11-29 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(
                default=False, help_text="Whether the message has been edited"
            ),
        ),
        migrations.CreateModel(
            name="MessageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_content",
                    models.TextField(help_text="The content before the edit"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the edit occurred"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        help_text="User who made the edit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message that was edited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message History",
                "verbose_name_plural": "Message Histories",
                "ordering": ["-edited_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "-edited_at"],
                        name="messaging_m_message_a83591_idx",
                    )
                ],
            },
        ),
    ]
