# Generated by Django 5.2.7 on 2025-11-29 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_message_edited_messagehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(
                default=False, help_text="Whether the receiver has read the message"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "read"], name="messaging_m_receive_6da6d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["parent_message", "-timestamp"],
                name="messaging_m_parent__2383f9_idx",
            ),
        ),
    ]
